/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_des_notes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MBONGO Wulfrid
 */
public class Connexion extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public Connexion() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Connexion");
    }

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_des_notes", "root", "");

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtpasswordconnect2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        matri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnconnectuser = new javax.swing.JButton();
        btnretour = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("MOT DE PASSE");

        txtpasswordconnect2.setBackground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONNEXION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 6, 396, 91));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Matricule");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 37));

        matri.setBackground(java.awt.SystemColor.activeCaption);
        matri.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        matri.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriActionPerformed(evt);
            }
        });
        jPanel1.add(matri, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 339, 37));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("MOT DE PASSE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 121, 37));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 316, -1, -1));

        btnconnectuser.setBackground(java.awt.SystemColor.activeCaption);
        btnconnectuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnconnectuser.setText("SE CONNECTER");
        btnconnectuser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnconnectuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconnectuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconnectuserActionPerformed(evt);
            }
        });
        jPanel1.add(btnconnectuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 150, 40));

        btnretour.setBackground(java.awt.SystemColor.activeCaption);
        btnretour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnretour.setText("Créer un compte");
        btnretour.setBorder(null);
        btnretour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });
        jPanel1.add(btnretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 134, 43));

        password.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 340, 40));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Statuts");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 121, 37));

        combo.setBackground(java.awt.SystemColor.activeCaption);
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enseignants", "Etudiant", "Administration" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 330, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_notes/thumb-1920-558952.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriActionPerformed

    private void btnconnectuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconnectuserActionPerformed

        try {
            Connect();
            pst = con.prepareStatement("select * from utilisateur where matricule=? and password=? and statut=?");
            pst.setString(1, matri.getText());
            pst.setString(2, password.getText());
            pst.setString(3, (String) combo.getSelectedItem());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String a = (String) combo.getSelectedItem();
                if ("Enseignants".equals(a)) {
                    String code = JOptionPane.showInputDialog(null, "Saisir le code d'acces resverver aux enseignants");
                    if (!code.equals("0852")) {
                        JOptionPane.showMessageDialog(null, "Erreur, veuillez reesayer");
                    } else {
                        JOptionPane.showMessageDialog(null, "Acces Accorder");
                        Operation A = new Operation();
                        A.setVisible(true);
                        this.hide();
                    }

                } else if ("Etudiant".equals(a)) {

                    Note_Tp A = new Note_Tp();
                    A.setVisible(true);
                    this.hide();
                }
                if ("Administration".equals(a)) {
                    String code = JOptionPane.showInputDialog(null, "Saisir le code d'acces resverver a l'administration");
                    if (!code.equals("0851")) {
                        JOptionPane.showMessageDialog(null, "Erreur, veuillez reesayer");
                    } else {
                        JOptionPane.showMessageDialog(null, "Acces Accorder");
                        Operation A = new Operation();
                        A.setVisible(true);
                        this.hide();
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "Erreur, veuillez reesayer");
                matri.setText("");
                password.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnconnectuserActionPerformed

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed

        NewUser newuser = new NewUser();
        newuser.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnretourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconnectuser;
    private javax.swing.JButton btnretour;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matri;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField txtpasswordconnect2;
    // End of variables declaration//GEN-END:variables

}
