/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_des_notes;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wulfrid MBONGO
 */
public class Note_f extends javax.swing.JFrame {

    /**
     * Creates new form Note_f
     */
    public Note_f() {
        initComponents();
        Data_Etudiant();
            rechercheEtudiant();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_des_notes", "root", "");

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableemploye = new javax.swing.JTable();
        txtResultat_Trouver = new javax.swing.JLabel();
        txtRechercheEtudiant = new javax.swing.JTextField();
        note1 = new javax.swing.JButton();
        matricule = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etudiant", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        tableemploye.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        tableemploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableemploye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableemploye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableemployeMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableemploye);

        txtResultat_Trouver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResultat_Trouver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResultat_Trouver.setText("Resultat");

        txtRechercheEtudiant.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rechercher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtRechercheEtudiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheEtudiantKeyReleased(evt);
            }
        });

        note1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        note1.setForeground(new java.awt.Color(255, 255, 255));
        note1.setText("Deconnexion");
        note1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtResultat_Trouver, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRechercheEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(note1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultat_Trouver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRechercheEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(note1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        matricule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matricule.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matricule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        jLabel1.setText("Taper votre nom ici pour votre note");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matricule, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableemployeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableemployeMousePressed
        int i = tableemploye.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableemploye.getModel();
        matricule.setText(model.getValueAt(i, 0).toString());
        //        Correcteur.setText(model.getValueAt(i, 1).toString());
        //        note.setText(model.getValueAt(i, 2).toString());
        //        poste.setText(model.getValueAt(i, 3).toString());
        //        telephone.setText(model.getValueAt(i, 4).toString());
        //        duree.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tableemployeMousePressed

    private void txtRechercheEtudiantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheEtudiantKeyReleased
        rechercheEtudiant();
    }//GEN-LAST:event_txtRechercheEtudiantKeyReleased

    private void note1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note1ActionPerformed
        // TODO add your handling code here:
        Connexion c = new Connexion();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_note1ActionPerformed
    public void Data_Etudiant() {
        //affichage 
        String[] Champ = {"MATRICULE", "NOM", "MATIERE", "NOTE_FINALE"};
        String[] afficher = new String[5];
        DefaultTableModel model = new DefaultTableModel(null, Champ);
        try {
            Connect();
            pst = con.prepareStatement("select matricule,nom,matiere,note_f from note");
            rs = pst.executeQuery();
            int i = 0;
            while (rs.next()) {
                afficher[0] = rs.getString("matricule");
                afficher[1] = rs.getString("nom");
                afficher[2] = rs.getString("matiere");
                afficher[3] = rs.getString("note_f");

                i++;
                model.addRow(afficher);
            }
            tableemploye.setModel(model);
            txtResultat_Trouver.setText(i + ":Resultat");

        } catch (Exception e) {
        }
    }

    public void rechercheEtudiant() {
        String[] Champ = {"MATRICULE", "NOM", "MATIERE", "CORRECTEUR", "NOTE_FINALE"};
        String[] afficher = new String[5];
        DefaultTableModel model = new DefaultTableModel(null, afficher);
        try {
            Connect();
            pst = con.prepareStatement("select matricule,nom,matiere,note_f from note where nom  like '%" + txtRechercheEtudiant.getText().trim() + "%' ");
            rs = pst.executeQuery();
            while (rs.next()) {
                afficher[0] = rs.getString("matricule");
                afficher[1] = rs.getString("nom");
                afficher[2] = rs.getString("matiere");
                afficher[3] = rs.getString("Correcteur");
                afficher[4] = rs.getString("note_f");

                matricule.setText(afficher[0]);

                model.addRow(afficher);
            }
            tableemploye.setModel(model);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Note_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Note_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Note_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Note_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Note_f().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel matricule;
    private javax.swing.JButton note1;
    private javax.swing.JTable tableemploye;
    private javax.swing.JTextField txtRechercheEtudiant;
    private javax.swing.JLabel txtResultat_Trouver;
    // End of variables declaration//GEN-END:variables
}
